Foreground false
TCPSocket 3310
TCPAddr 127.0.0.1
MaxFileSize 20M
MaxScanSize 20M
StreamMaxLength 20M
MaxThreads 4
ReadTimeout 30
CommandReadTimeout 10
SendBufTimeout 30
LogClean false
LogTime false
LogVerbose false
LogFile /dev/null
DatabaseDirectory /var/lib/clamav
